# Generated by Django 5.1.1 on 2024-09-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IP16M', 'iphone16 pro max'), ('IP16PR', 'iphone16 pro'), ('IP16PL', 'iphone16 plus'), ('IP16', 'iphone16 '), ('IP15M', 'iphone15 pro max'), ('IP15PR', 'iphone15 pro'), ('IP15PL', 'iphone15 plus'), ('IP15PL', 'iphone15 plus'), ('IP15', 'iphone15 '), ('IP14M', 'iphone14 pro max'), ('IP14PR', 'iphone14 pro '), ('IP14L', 'iphone14 plus'), ('IP14', 'iphone14 ')], default='General', max_length=6),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
