# Generated by Django 5.1.1 on 2024-09-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_category_product_composition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IP16', 'iphone16 '), ('IP15', 'iphone15 '), ('IP14', 'iphone14 ')], default='General', max_length=6),
        ),
    ]
