# Generated by Django 5.1.1 on 2024-10-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IP16', 'iphone16 '), ('IP15', 'iphone15 '), ('IP14', 'iphone14 '), ('IP14', 'iphone13 ')], default='General', max_length=6),
        ),
    ]
