# Generated by Django 5.1.1 on 2024-10-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('IP16', 'iphone16 '), ('IP15', 'iphone15 '), ('IP14', 'iphone14 '), ('IP14', 'iphone13 '), ('IP12', 'iphone12 '), ('IP11', 'iphone11 '), ('IP11', 'iphone11 '), ('IP10', 'iphone10 '), ('IP9', 'iphone9 '), ('IP8', 'iphone8 '), ('IPR15', 'iphone_refubrish15'), ('IPR14', 'iphone_refubrish14'), ('IPR13', 'iphone_refubrish13'), ('IPR12', 'iphone_refubrish12'), ('IPR11', 'iphone_refubrish11'), ('IPR10', 'iphone_refubrish10'), ('IPR9', 'iphone_refubrish9'), ('IPR8', 'iphone_refubrish8')], default='General', max_length=6),
        ),
    ]
